### ISSUE TITLE
Change member variable prefix in AttendanceActivity.java

### ISSUE THREAD

**Issue by abhijitparida** [abhijitparida/bunk#12]
Prefix all member variables in AttendanceActivity.java with `this.` and remove the `m` prefix.

For example,

```
mContext
```

becomes

```
this.context
```

File location: /app/src/main/java/app/abhijit/iter/AttendanceActivity.java

If this is your first pull request, read this article: (https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). Make sure all test cases pass before submitting your pull request.

Happy Hacktoberfest! 🔥

**Comment by Redarcher9** [comment]
Hii..can I work in this issue?

**Comment by abhijitparida** [comment]
Yeah sure

**Comment by Redarcher9** [comment]
Hi..how do i check if its passing all the test cases?

**Comment by abhijitparida** [comment]
Right click on the `test` directory in Android Studio and click on `Run...`

Or, you can just execute `gradlew test` on the command line.

See: https://www.youtube.com/watch?v=dlWjn4QrVK4

**Comment by Redarcher9** [comment]
Thnks @abhijitparida I'll send a pull request by tonight as I would need to install Android studio and Developer tools.

**Comment by abhijitparida** [comment]
No problem.

**Comment by Redarcher9** [comment]
hi...i am getting this error after running the gradle test on command line

Task :app:compileDebugJavaWithJavac 
/home/redarcher9/Documents/op/bunk/bunk/app/src/main/java/app/abhijit/iter/AttendanceActivity.java:229: error: cannot find symbol
                this.SharedPreferences.edit().putString("pref_student", null).apply();
                    ^
  symbol: variable SharedPreferences
/home/redarcher9/Documents/op/bunk/bunk/app/src/main/java/app/abhijit/iter/AttendanceActivity.java:397: error: cannot reference this before supertype constructor has been called
            super(this.context, R.layout.item_subject, subjectViews);
                  ^
/home/redarcher9/Documents/op/bunk/bunk/app/src/main/java/app/abhijit/iter/AttendanceActivity.java:397: error: cannot find symbol
            super(this.context, R.layout.item_subject, subjectViews);
                      ^
  symbol: variable context
/home/redarcher9/Documents/op/bunk/bunk/app/src/main/java/app/abhijit/iter/AttendanceActivity.java:399: error: cannot find symbol
            mLayoutInflater = LayoutInflater.from(this.context);

I think it has something to do with inheritance

**Comment by abhijitparida** [comment]
Did you change the `mSharedPreferences` declaration to `sharedPreferences`? You have to refer to it as `this.sharedPreferences`.

**Comment by Redarcher9** [comment]
Made some changes and now the build is successful..
![screenshot_20181012_225628](https://user-images.githubusercontent.com/19843336/46884285-31afd280-ce72-11e8-8a9b-bf00fee86794.png)

**Comment by Redarcher9** [comment]
I sent a PR. Please check it
