### ISSUE TITLE
Change member variable prefix in LoginActivity.java

### ISSUE THREAD

**Issue by abhijitparida** [abhijitparida/bunk#13]
Prefix all member variables in LoginActivity.java with `this.` and remove the `m` prefix.

For example,

```
mContext
```

becomes

```
this.context
```

File location: /app/src/main/java/app/abhijit/iter/LoginActivity.java

If this is your first pull request, read this article: (https://www.digitalocean.com/community/tutorials/how-to-create-a-pull-request-on-github). Make sure all test cases pass before submitting your pull request.

Happy Hacktoberfest! 🔥

**Comment by jashasweejena** [comment]
Hello! Can I work on this issue?

Thank you!

**Comment by abhijitparida** [comment]
Yeah sure!

**Comment by abhijitparida** [comment]
Add it, but submit a different pull request for that.

**Comment by jashasweejena** [comment]
> Add it, but submit a different pull request for that.

Did do that. Can you please check?

**Comment by jashasweejena** [comment]
Another problem I was facing was even though the app builds fine and installs on my device, yet still, I weirdly am not able to log in using my credentials. I tried uninstalling it and installing the one on play store and it works just fine. I guess some previous commit broke the login functionality. I did not touch anything else but just fix gradle sync. 

Thank you!

**Comment by abhijitparida** [comment]
> Did do that. Can you please check?

Merged 👍 



> Another problem I was facing was even though the app builds fine and installs on my device, yet still, I weirdly am not able to log in using my credentials. I tried uninstalling it and installing the one on play store and it works just fine. I guess some previous commit broke the login functionality. I did not touch anything else but just fix gradle sync.
> 
> Thank you!

Debug builds are configured not to make API requests to ITER servers. You can use any username (provided that it contains 10 digits) and the password must be `password`.

See: https://github.com/abhijitparida/bunk#contributing

**Comment by jashasweejena** [comment]
> Debug builds are configured not to make API requests to ITER servers. You can use any username (provided that it contains 10 digits) and the password must be `password`.

Ahh. Would get on working through this issue right away! 
I'm sorry I did not read the contributing guidelines.

Thank you!
